### PR TITLE
Depend on request header when possible

### PR DESCRIPTION
**Pull request by deigote**

### CODE REVIEW

**Comment by inakianduaga** [comment]
While I agree with the PR itself (not sure why it depended on the whole `Request` instead of `RequestHeader`, this was making it harder than necessary to use toggling in Play Filters (needed artificial wrapping). This is a breaking change on the API, as such it should be published ideally under a major version bump so it's clear for everyone that when they upgrade they will most likely have to fix the integration

**Comment by deigote** [comment]
I think the usage of `Request` was a mistake originated by the fact that the rest of the play support is based on one of this clunky `ActionBuilder` and `WrappedRequest` mechanism, and in there you need the full `Request`. Probably they didn't realise that in the concrete `PlayToguruClient` the lighter interface of `RequestHeader` could be used.

Regarding the version number, fine by me. I don't have a clue about the version number strategy of toguru, since right now the dependency that I use reads `"1.1.1-f46aec3231759934b75023bf38026fe730803dc4"`. I guess it's a combination of `git.baseVersion := "1.1.1"` and the git sha?

Would it be `2.0.0` then @inakianduaga ? Once we figure out an owner, we can go for that if it makes sense for them...

**Comment by inakianduaga** [comment]
@deigote Another thing, for backwards compatibility reasons, would it be too hard to overload the methods to accept both `Request` & `RequestHeader`? That would save everyone the work of having to update  the codebases

**Comment by deigote** [comment]
@inakianduaga `Request` is a subtype of `RequestHeader`. If the API is well designed, any method accepting a `Request` should work with a `RequestHeader`, so it should be transparent. Also, many methods need to keep the `Request` as, as said before, they use the `ActionBuilder` thing to offer a `ToggledAction` or similar.  

Anyways, I'd be happy to test this locally, as the changes I had to do were too short. Tests are green, but I don't know the project well enough to know if that's good enough. I guess I'd need to package the lib and add it as a local dependency somehow.

**Comment by rtimush** [comment]
That's a pity that we missed a chance to include this PR in the 2.0.0 release.

**Pull request closed without merging**
